# Generated by Django 5.1.2 on 2024-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
