# Generated by Django 5.1.2 on 2024-10-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='roll_number',
            field=models.CharField(max_length=100),
        ),
    ]
